name: Update Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish DevContainer Feature"]
    branches:
      - master
    types:
      - completed

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: documentation
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generate Documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          base-path-to-features: "./src"

      - name: Create a PR for Documentation
        id: push_docs
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          set -e
          echo "Starting documentation update..."

          # Configure git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git config pull.rebase false

          # Get the default branch dynamically
          DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')
          echo "Default branch is: $DEFAULT_BRANCH"

          # Create a new branch
          branch="automated-docs-update-$GITHUB_RUN_ID"
          git checkout -b "$branch"
          message="Automated documentation update"

          # Add and commit generated docs
          git add */**/README.md
          git commit -m "$message [skip ci]" || export NO_UPDATES=true

          # Push and create PR if there are changes
          if [ "$NO_UPDATES" != "true" ]; then
            git push origin "$branch"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              /repos/${GITHUB_REPOSITORY}/pulls \
              -f title="$message" \
              -f body="$message" \
              -f head="$branch" \
              -f base="$DEFAULT_BRANCH"
          else
            echo "No documentation updates to commit."
          fi
